### ISSUE TITLE
PH Values stimmen nicht

### ISSUE THREAD

**Issue by adnet-solutions** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#11]
ich nutze den Atlas PH Sensor im Pool in einer Strömungskammer für genau diese Probes.

Die Werte hole ich über den Adapter alle 30 Sekunden. Die Werte schwanken aber extrem so das man nicht weiss was der wirkliche Wert ist.  Anbei mal ein CSV File mit einem Ausschnitt.

Der Poollab als externes digitales Messgerät sagt übrigens 7,32 momentan so das ich auch davon ausgehe das eigentlich irgendwas um 7,3 stimmen müsste.

[0x63 PoolPH.csv](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/files/12081809/0x63.PoolPH.csv)

**Comment by Buzze11** [comment]
Hallo Bicmac, 

auch hier die gleiche Frage wie im letzten Issue. Hast du die Werte einfach mal über command line abgefragt? Ich würde vermuten sie schwanken dort genauso. Der Adapter liest genau wie die command line direkt vom Ezo Board die gemessenen Werte. Durch die Strömungskammern werden hier vermutlich Schwankungen in den Messungen sein. Ich kann leider nicht sagen, wie Poollab an dieser Stelle arbeitet. Ich denke aber, dort werden aus allen Werten arithmetische Mittelwerte genommen, und dann dargestellt. Deshalb sieht man dort die Schwankungen nicht. Wenn du die Werte mit Grafana aus der InfluxDB visualisierst, kannst du genau diese Funktion nachbilden. Grafana selbst bietet in seinen Visualisierungen exakt diese Funktionen an der Schnittstelle zur Datenbank an.

**Comment by Buzze11** [comment]
Deine Werte ergeben aus der Tabelle 82,968/13= 6,38 im Mittelwert. Zur Kalibrierung bzw. zur Güte bzw. Funktionalität kann ich weil ich dein System kenne natürlich so nichts sagen. Aber die Abweichung könnte von der Kalibrierung kommen. 


Je mehr Werte zur Mittelwertbildung genommen werden, desto genauer wird das Messergebnis.

**Comment by adnet-solutions** [comment]
Das system ist neu kalibriert.
Was mich wundert ist das es eine weile die richtigen werte anzeigt und dann regelmässig quasi einmal absackt. 
ich logge jetzt mal über macht die werte mit da ist die Poolpumpe aus und der Probe steht quasi im stillem Wasser Strömungskammer.
So kann ich die Probes nur nicht verwenden denn wie soll ich denn den richtigen aktuellen Wert bestimmen um zu wissen ob und wieviel ich nachregulieren muss.
Ich könnte nur ggf eine stunde alle 30 sekunden messen und dann den gleitenden Mittelwert über die Stunde bilden. Das wären dann 120 messwerte.

**Comment by Buzze11** [comment]
Ich meinte mit meiner Aussage zur Strömungskammer auch nicht dass das nicht gehen sollte. Das muss ja irgendwie gehen. Es gibt ja viele, die die Atlas Sensoren für Pool verwenden. Ich hab damit leider keine Erfahrung im Poolbereich. Vielleicht macht es Sinn wenn Du hierzu mal in den Foren postest oder auch im ioBroker Forum. Ich habe den Adapter so konzipiert und auch die Software so geschrieben, dass er die Werte ohne sie zu verändern direkt von den Sensoren durchreicht, damit man sie in einer Datenbank mitloggen und auswerten kann. Um es möglichst flexibel zu halten. Deshalb kam auch mein Hinweis mit der Command line im Vergleich. Ich gehe davon aus, dass die Werte, die du angezeigt bekommst auch so von der Sensorik geliefert werden. Wenn die Werte allerdings eine Weile stimmen und dann einsacken, spricht das meiner Meinung nach aber auch für möglicherweise äußere Einwirkung.. z.B. Luftblasenbildung am Sensor oder irgendwie sowas. Arbeitest du gleichzeitig mit der Temperaturkalibrierung? Also setzt du die entsprechende Temperatur für den PH Sensor am entsprechenden State Objekt?

**Comment by Buzze11** [comment]
Hast du mal im Datenblatt der Sonde nachgeschaut, ob sie für die Anwendung in einer Strömungskammer oder generell passend zu deiner Anwendung und dem Einbau passt? Die haben ja mehrere Sonden im Portfolio. Also nur um sicher zu gehen.

**Comment by adnet-solutions** [comment]
Ja ich arbeite mit der Temperaturkalibrierung. dazu setze ich minütlich auch die aktuell gemessene Wassertemperatur.
Das Datenblatt schaue ich mir morgen nochmal an und werd auch mal bei Atlas direkt nachfragen woran das liegen kann.
Ich hatte das ganze vor 2 Jahren schonmal mit FHEM am laufen und da eigentlich nicht die Probleme. Kann aber wein das das ein anderer Probe war da der neue jetzt auch nen SMA anschluss anstatt eines BNC hat. BNC hatte ich so garnicht mehr gefunden.

**Comment by Buzze11** [comment]
Ich würde die Temperatur Calibration nicht ganz so häufig setzen. Der Sensor rechnet sonst stetig die Werte über den Temperatur Koeffizienten um. Ich habe das über einen Schnipsel Java Code und dem Java Adapter bei mir über eine Hysterese gesteuert. Ich mache das Zeitunabhängig, also nicht per Timer. Ich reagiere dort beispielsweise nur auf Änderungen der Temperatur in der ersten Kommastelle und nicht im hinteren Nachkommabereich. Nur wenn sich die Temperatur entsprechend ändert, setze ich die Kalibrierung.

**Comment by Buzze11** [comment]
Hi bicmac. Gibt es Neuigkeiten? Konntest Du die Probleme lösen?

**Comment by adnet-solutions** [comment]
Hi, leider noch nicht. Selbst mit einem gleitendem Durchschnitt über den 1h Zeitraum (120 messwerte) stimmen die werte nicht wirklich.
Ich bin aber mit Atlas in Kontakt das die mal checken ob ich einen Denkfehler habe. 
War heute aber auch unterwegs u d konnte nicht viel testen. muss morgen mal weitermachen.

**Comment by adnet-solutions** [comment]
@Buzze11 , ich habe mal mit Atlas geschrieben. Die vermuten zu viel Noise in meinem setup. Es sieht auch so aus das die Werte Nachts wenn nichts läuft stabieler sind. 
die idee wäre nun nur zu geziehlt zu messen wenn die Pumpe und die Heizung aus ist. 
Daher auch mein request den Probe über eon Object und nicht nur über die Einstellungen der Instanz deaktivieren und aktivieren zu können. Dann könnte ich das gut mit blockly steuern und müsste dann nicht mit temporären Hilsdatenpunkten arbeiten als Workarround.

**Comment by Buzze11** [comment]
Hi bicmac,

du kannst auch mal versuchen Ferrit-Kerne um die Leitungen zu machen. Hauptsächlich wichtig in der Spannungsversorgung.

**Comment by adnet-solutions** [comment]
Gute idee. momentan hab ich nen workarround das ich „nur“ alle 3 stunden für 5min messe und da in der zeit alles abschalte und dann den durchschnitt bilde über die 5 minuten. Die Werte scheinen auch einigermassen plausibel zu sein.

**Comment by Buzze11** [comment]
Das klingt doch gut. Mit anderen Worten hat sich das Issue dann doch damit erledigt, und es liegt am Setup korrekt? Kannst du das Issue dann closen bitte?
VG Thomas

**Comment by adnet-solutions** [comment]
@Buzze11 , nur als Kommentar. Ich habe jetzt glaube ich die Ursache gefunden.
Wenn ich das Poolwasser (also das Messmedium) auf dem selben Potential habe wie die BNC außenhülle des Probes (also einfach ein Kabel zw Wasser und BNC außenhülle vom Probe) dann hören die Schwankungen fast auf bzw werden maßgeblich reduziert. Werde das mal weiter beobachten.

**Comment by Buzze11** [comment]
Das spricht aber dafür, dass in dem Isolated Setup etwas nicht stimmt. Ich würde davon ausgehen, dass bei Full isolated andernfalls keine Potentialunterschiede auftreten sollten. Vorsicht mit dem Workaround! Wenn höhere Potentialschwankungen im Wasser auftreten (Blitzeinschlag, statisch) , dann wird diese Spannung auch auf GND der Elektronik übertragen, und zerstört ggf. deine Sensorik und Elektronik. 

VG Buzze11

**Comment by adnet-solutions** [comment]
Ja ich verstehe das auch nicht, denn laut werbung von Atlas ist ja das Whitebox T3 mit den EZO die ich benutze fully isolated.
Werd am WE mal weiter experimentieren. Ggf reicht es ja nur die Messkammer mit nem Erdungsapiess zu erden.

**Comment by Buzze11** [comment]
Hi @bicmac 
nur 2 der 3 Steckplätze sind isolated. Da musst du drauf achten. Vielleicht ist da schon dein Fehler.. 😉

**Comment by adnet-solutions** [comment]
Nein habe genau die 2 bzw momentan sogar nur einen davon belegt. Da hatte ich schon drauf geachtet.

**Comment by Buzze11** [comment]
Hatte übrigens vergessen zu erwähnen, dass die elektrische Verbindung von GND des Raspberry mit dem Wasser unter Umständen auch lebensgefährlich ist. Nicht auszudenken was passiert, wenn die Fremdspannung dann z.B. auf dem GND aufkommt (Netzteil kaputt oder sonstiges) und auf das Wasser übertragen wird, was nicht geerdet ist.

**Comment by adnet-solutions** [comment]
Ja da hast du wohl recht. Habe daher die Verbindung wieder entfernt. Aber Atlas hatte mir nochmal geschrieben und meinte ich soll mal nur in der nähe des Messfühlers eine Erdverbindung zum Wasser herstellen. Also hab ich mal nen Erdanker an die Messkammer (die hatte ja sogar einen Erdungsanschluss vorgesehen) angeschlossen. Bisher sieht es gut aus. Die Werte Schwanken nur um 0,002 was vollkommen gut ist. Warum ich die Messkammer ich den Erdungsanschluss der Kammer vorher vergessen hatte weiss ich auch nicht. Hab die Schraube wohl übersehen und natürlich nicht die Anleitung gelesen. Also sass das problem wie es aussieht wieder mal 50cm vor dem Bildschirm. Bin mal gespannt ob die Werte so stabiel bleiben die nächsten tage.

**Comment by Buzze11** [comment]
Das klingt doch sehr gut. Dann drücke ich die Daumen. Gehe aber stark davon aus, dass das korrekt ist. Zumal die Erdung des Messmediums immer wichtig ist. Allein wegen Statik der Verrohrung. 
VG
