### ISSUE TITLE
Keine Installation

### ISSUE THREAD

**Issue by Tuerlich86** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#12]
Hi,

ich hab ein neues Bullseye aufgesetzt und direkt dort iobroker installiert, alles ist auf neustem Stand jedoch kann ich den Adapter nicht installieren. Mein System stürzt ab. 

![grafik](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/assets/90872396/e75a19d2-b4d9-4f7f-ace0-bd6790577360)

**Comment by Buzze11** [comment]
Hi Tuerlich, 

ich kann dies nicht reproduzieren. Kannst du bitte den kompletten Error Log hier hinzufügen, der in der Kurzversion angemerkt ist?

**Comment by Buzze11** [comment]
Hi @Tuerlich86, könntest Du die Logs bitte noch liefern? Ich habe allerdings in anderen Foren gelesen, dass die neueste Version von ioBroker buggy ist. ggf. liegt es auch daran. 

VG Buzze11

**Comment by Buzze11** [comment]
Closed due to missing Log Information which I have requested, and no Answer from creator

**Comment by Tuerlich86** [comment]
Hey, sorry war gerade nicht erreichbar. Ich hab es jetzt mehrmals mit neuem Iobroker installationen probiert aber keine Chance der Pi Zero2 hängt sich jetzt auf und arbeitet ewig ohne Fehlermeldung und Log mit einem Banana Pi 2 passiert genau das gleich. Hab auch ein Iobroker Image probiert und ein Raspian und auf dem Banana ein Armbian. Gerne können wir auch über discod texten tuerlich86
