### ISSUE TITLE
Feature request: Atlas Presure Sensor support

### ISSUE THREAD

**Issue by adnet-solutions** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#14]
Ich würde gern auch diesen Atlas Druck Sensor hier auslesen um Quasi den Kesseldruck meiner Filteranlage zu messen. Meinst Du man könnte da relativ einfach was einbauen?

https://atlas-scientific.com/product/pressure-sensor/

**Comment by Buzze11** [comment]
Einfach ist da leider gar nichts. Die Implementierung ist immer mit Aufwand verbunden. Ich mache mal nen groben Aufschlag und würde sagen rund 20-30 Stunden Entwicklung vom Hardwaretreiber bis in den Adapter sind nötig. 
Damit bekommst Du auch mal eine gute Einschätzung, wie viel Zeit der gesamte Adapter geschluckt hat ;)

Vielleicht irgendwann mal, und auch nur dann, wenn ich Zeit finde, und das ganze auch für mehrere User Sinn macht. 
Nicht böse gemeint, aber ich versinke sonst in Anfragen...

**Comment by Buzze11** [comment]
Hi @bicmac, 
lass den FR ruhig mal offen. vielleicht melden sich ja noch ein paar Interessenten.. ;)

**Comment by Buzze11** [comment]
Hi @bicmac,
lass den FR ruhig mal offen. vielleicht melden sich ja noch ein paar Interessenten.. ;)

**Comment by adnet-solutions** [comment]
ok danke. Falls du für die Implementierung HW brauchst (den EZO und den Probe) könnte ich dir die ggf leihweise für die Dauer der Implementierung dann zur Verfügung stellen. Bräuchte Sie danach nur wieder da ich sie auch net doppelt kaufen will dann.

**Comment by Buzze11** [comment]
Ja mal schauen, die Pumpe hab ich auch ohne Hardware implementiert, und mir Rückmeldung von einem user geholt. Da hab ich gestern nochmal Bugs gefixt. Hab mir aber jetzt auch ne Pumpe bestellt.

**Comment by Buzze11** [comment]
Hallo @bicmac,
ich habe mir etwas Zeit genommen, und zumindest schon mal den hardware Treiber implementiert. Mal schauen wann ich zu dem Rest komme.. ;)

**Comment by Buzze11** [comment]
Hallo @bicmac,

Implementierung für PRS ist drin. Viel Spaß damit. Ich hoffe jetzt hab ich mal ne Donation verdient! ;)
