### ISSUE TITLE
Frage:  mehrere RTD

### ISSUE THREAD

**Issue by adnet-solutions** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#15]
Hi,
leider kann ich Dich nur hier erreichen (das Reposoitory hat keinen Diskussionbereich) daher so die Frage. Unterstützt der Adapter mehrere RTD Sensoren? Ich müsste bei mir an 2 Stellen messen und daher würde ich gern 2 RTD EZO anschliessen. Geht das mit dem Adapter?

**Comment by Buzze11** [comment]
Hi @bicmac, 
ja, das ist möglich. Die Anzahl (auch gleicher Sensortypen) ist nicht begrenzt. Wichtig ist nur, dass du dann unterschiedliche I2C Adressen für gleiche Typen vergibst, da diese von Atlas immer mit der gleichen Default Adresse ausgeliefert werden. 
Mit anderen Worten. Wenn du über die Adapterfunktion die default Adresse des jetzigen Sensors abänderst, bevor du den zweiten einsetzt, kannst du einfach einen weiteren mit der default Adresse einsetzen und im Betrieb nehmen. 
VG

**Comment by Buzze11** [comment]
Closed as answered
