### ISSUE TITLE
Pause Funktion pausiert PH Messung nicht 

### ISSUE THREAD

**Issue by adnet-solutions** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#16]
Ich pausiere die Messung sobald mein Poolroboter läuft (er verfälscht die Werte).
Nun habe ich heute festgestellt das atlas-scientific-ezo-i2c.0.0x63.PH_Value trotz Pause atlas-scientific-ezo-i2c.0.0x63.IsPaused = true upgedated wird. Ich hätte erwartet das sich die Werte dann nicht ändern.

**Comment by Buzze11** [comment]
Hi @bicmac,

welche Version nutzt Du? Ich habe dies gerade bei mir getestet. Ich kann keinen Fehler feststellen. Wie setzt du den Wert "paused" in dem State? Wird der State korrekt angezeigt in den Objekten?

![image](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/assets/35816547/601d18e6-35cb-426b-8f69-c21ead467dd4)

**Comment by adnet-solutions** [comment]
Hi,
ich benutze Version 2.2.2
ich setze das ganze über ein Blockly und er zeigt dann auch den status an. Werds nach meinem urlaub nochmal testen. Bin nur grad unterwegs im Ausland.

<img width="568" alt="image" src="https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/assets/44036062/fcc1438e-c119-4393-9a26-591673aa1bf7">

**Comment by Buzze11** [comment]
Versuch auch mal bitte händisch zu setzen als Gegentest. Also in der Objekt-View direkt auf dem State den Wert setzen.

**Comment by Buzze11** [comment]
HI @bicmac, hast Du ein Update hier? Ich kann es definitiv nicht nachstellen. Bitte beachten, dass der Pause State nur temporär ist. Nach Adapter restart wird der Pause State wieder auf "unpaused" gesetzt

**Comment by adnet-solutions** [comment]
Hi,
Ich bin momentan noch im Urlaub und erst in 2 Tagen wieder daheim. Dann kann ich ggf nochmal testen

**Comment by adnet-solutions** [comment]
hi,
so ich habe nun nochmal auf die neueste Version upgedated und nochmal getestet. Zumindest wenn ich den paused status direkt über die AdminUI setze geht es jetzt. Ich weiss nicht warum es vorher nicht ging.
Ich mache den Bug mal zu und wenn es nochmal auftritt halt wieder auf. Danke Dir.
