### ISSUE TITLE
Esp or other Pi?

### ISSUE THREAD

**Issue by Tuerlich86** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#2]
Hi,

Is it possible to send the data from an other pi or an ESP ? The pool is not near my Server 😅

**Comment by Buzze11** [comment]
Hi Tuerlich,

no for the moment I have not implemented that into my project as I have`nt had the needs for it. As it is possible that one  can have multiple instances of ioBroker running  combined in one network the pain should not be to big. I for example have more than one pi running in my environment. One of those close to the pool. But you can contribute to the project and extend it if you want. ;)

BR Buzze

**Comment by Buzze11** [comment]
Hi Tuerlich, 

please create a Feature request. So that other contributors may implement that in future.

BR Thomas
