### ISSUE TITLE
Danke

### ISSUE THREAD

**Issue by ZeroQool007** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#3]
Hallo, genau so ein Projekt habe ich gesucht. Bist du zufällig auch im Pool-Forum unterwegs und nutzt du das auch für die Pool-Technik?

Danke

Gruß

**Comment by Buzze11** [comment]
Hallo, nein, ich bin nicht im Pool Forum. Ich möchte es zur Wasserkontrolle in einem Angelverein einsetzen. Aber ich denke der Großteil hier ist eher an der Poolsteuerung interessiert. Sollte machbar sein ;)

VG
