### ISSUE TITLE
Adressen Zuordnung

### ISSUE THREAD

**Issue by ZeroQool007** [Buzze11/ioBroker.atlas-scientific-ezo-i2c#4]
Hallo, danke für das geile Projekt.

Ich benötige bei der Konfiguration Hilfe. Bei mir findet der 3 Devices

0x62, 0x63, 0x66 u nun muss ich den DeviceType angeben. Jetzt ist die Frage woher weiß ich das 0x62  zB für die PH Sonde ist. Es könnte genauso gut der 0x66 sein. Danke

Gruß

**Comment by ZeroQool007** [comment]
Habe bei Atlas Scientific folgende Info gefunden:

![image](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/assets/12768323/fabde3da-86dc-4aab-8264-98fefb886d81)

**Comment by Buzze11** [comment]
Hallo, die Tabelle sind nur die default Werte. Die EZO's können von der Adresse her umprogrammiert werden. Nachdem ein Typ ausgewählt wurde (egal welcher) erscheint eine Taste auf der Admin Oberfläche. "Find Device". Mit einem Klick darauf fängt die LED vom Modul mit der entsprechenden Adresse an zu blinken. Damit kann dann herausgefunden werden welches Modul welche Adresse hat. 😉

**Comment by Buzze11** [comment]
Falls das geholfen hat, bitte das Issue wieder schließen als resolved. In der Hilfe stehen noch einige Hinweise.

Viele Grüße und viel Spaß mit dem Adapter. 👍

**Comment by ZeroQool007** [comment]
Leider hat die Funktion bzgl. Blinken nicht funktioniert. Es leuchten bei mir alle 3 durchgehend. PH, Redox, Temperatur. 

Deshalb habe ich den Issue erstellt, weil mit dir Ideen ausgingen.

**Comment by ZeroQool007** [comment]
Mit dem Button Find EZO Board hat es doch geklappt. War nur schwierig zu differenzieren, weil alles regelmäßig am blinken war.

Habe alles sauber kalibriert, aber sobald die Sonden mit dem Pool Wasser in Kontakt kommen stimmen die Werte hinten und vorne nicht. 

REDOX: 390mV
PH: 4.2

Poolab 1.0 sagt
FCL: 2.2
PH: 7.4

**Comment by Buzze11** [comment]
Bei mir stimmen die Werte ziemlich genau mir denen einer Handsonde überein. Mal davon ab werden alle Werte "unbearbeitet" vom I2C Bus gelesen, und direkt an ioBroker durchgereicht. Sind die EZO Boards alle Isolated montiert?

**Comment by ZeroQool007** [comment]
Ja, sind Sie. Ich habe eben noch einmal neu kalibriert. Immer noch das gleiche Probleme. Deshalb habe ich jetzt mal neue Sonden bestellt. Die lagen noch original verpackt 3 Jahre im Schrank. In dem Sinn eigentlich nie benutzt und zusätzlich in der Aufbewahrungsflüssigkeit aufbewahrt. Bei den Kalibrierflüssigkeiten stimmen eigenartigerweise die Werte. Dachte liegt vllt an der Messzelle das die zu stark durchströmt wird, aber habe die Sonden mal in einen Becher Poolwasser reingelegt. Kommen auch nur unsinnige Werte. 

Keine Ahnung, ob es damit zusammenhängen könnte, aber das ganze läuft bei mir auf einem Raspberry 4 Board und als Netzteil 5V mit 2.5A. 

Gruß

**Comment by Buzze11** [comment]
Mit dem Find Device Button sollte eigentlich nur die LED des EZO Boards blinken, welches die entsprechende Adresse hat. 
Es ist aber ausgeschlossen, dass dass ein Sensor an einem falschen EZO Board hängt, oder? 

Man kann auch im Terminal direkt per Python Script die Werte der Sensoren auslesen. Also direkt über den I2C Bus per Script von Scientific. Wenn es dort die gleichen falschen Werte sind, liegt es definitiv am Sensor

**Comment by Buzze11** [comment]
![Bildschirmfoto 2023-06-28 um 21 35 33](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/assets/35816547/93198408-b66f-487b-8e54-7cc569b387d9)

Hier kannst Du sehen, wie ich einmal per i2c sample code von atlas per Terminal die Werte abrufe und einmal über den ioBroker Adapter. Die geringe Abweichung bei den Werten ist die Messdifferenz durch der Zeitversatz der Messung die im Abstand von ca 15s ausgelesen wurden (starten vom adapter und poll Zyklus, dann stoppen des Adapters und dann anschließend auslesen per Terminal. Die werte sind aber definitiv gleich. Damit kann ich sicherstellen, dass die Werte vom Adapter übereinstimmen mit den Werten des original atlas sample codes..

**Comment by Buzze11** [comment]
Du kannst dies gern mal bei dir verifizieren. Folgende Anleitung im Bereich I2C gibt Dir hier die Anleitung wie es geht..
https://files.atlas-scientific.com/pi_sample_code.pdf

**Comment by ZeroQool007** [comment]
Habe jetzt neue Sensoren bestellt. ORP stimmt nun, denke ich mal, aber PH ist bei 5.5 und Messgerät sagt 8.2. Von der Farbe würde ich auch auf 8 tippen. Bin nun deinem Rat gefolgt und bekomme bei der PH Sonde folgende Fehlermeldung:


>> WARNING: device at I2C address 99 has not been identified as an EZO device, a                                         nd will not be queried
--> ORP 98 Redox
 - RTD 102 Temperatur

Glaube ich mal die Hardware prüfen, aber komischerweise kommen die PH Werte im iobroker an, also man sieht die WErte ändern sich sobald ich die Sonde ins Wasser oder Kalibrierflüssigkeit tauche. Nur in der Kalibrierflüssigkeit stimmen die Werte, aber sobald normales Wasser, sei es Leitungswasser oder Poolwasser passt es hinten und vorne nicht.

**Comment by ZeroQool007** [comment]
Habe mal den PI restartet. Auch wieder komisch. Zwischendurch kommen die ERRORs, aber generell ist PH immer noch falsch:

![image](https://github.com/Buzze11/ioBroker.atlas-scientific-ezo-i2c/assets/12768323/fb0bc8e5-e687-40af-a6ce-c33f754f6884)
`

**Comment by Buzze11** [comment]
Hast du die I2C-Bus Geschwindigkeit mal gecheckt? Mal bitte bei Google suchen, die war in irgend einer Config Datei..

Des Weiteren bitte mal Fehlerquellen minimieren und nur das EZO Board für PH aufsetzen um
auszuschließen dass zwei Geräte die gleiche Adresse haben oder sowas... Alle anderen Sensoren mal runter

VG Buzze11

**Comment by Buzze11** [comment]
Was halt schon komisch war, war deine Aussage dass es schwer war mit der Zuordnung weil alles geblinkt hätte.. es darf nur das EZO Board blinken für dass du den Button klickst in der UI. Ich würde dir auch empfehlen, den Polling Zyklus heraufzusetzen bei der Menge an Sensoren auf min 30 Sekunden. Man kann in der Kommandozeilenausgabe ohne ioBroker sehen, dass Timingprobleme im EZO Speicher passieren. In einer der unteren Ausgaben deines Screenshot wird zum Beispiel der Devicestatus statt des Wertes wie in den anderen Zeilen dargestellt.. und bitte auch nicht parallel betreiben, also nicht ioBroker und gleichzeitig die Scripte von Atlas auf der Kommandozeile verwenden, weil die Abfrage auf dem Bus sonst nicht synchron abgearbeitet wird

**Comment by ZeroQool007** [comment]
Vielen Dank für deine Hilfe!

Bin das ganze noch einmal durchgegangen und ich denke ich habe beim i2c toggle nicht jeweils den Jumper auf PH/ORP gesetzt. Das habe ich gemacht und jetzt leuchtet das korrekte EZO Board, wenn ich auf den Button klicke. Die Error konnte ich wie du gesagt hast damit umgehen, dass ich den iobroker deaktiviert habe.

Ich habe einen Becher mit Leitungswasser genommen und bekomme folgende Werte:

> Success ORP 98 Redox: 265.3
> Success pH 99 PH: 7.377

Nun nehme ich einen Becher mit Pool-Salzwasser, 3ppm bekomme ich folgendes:

> Success ORP 98 Redox: -121.7
> Success pH 99 PH: 4.505

Poollab Becher mit Leitungswasser:

> PH: 7,64
> FCL: 1.69

Die PH Abweichung könnte hinkommen, weil im Debug Modus der Sonde kommen unkalibrierte Werte? Das konnte ich mit den 3 verschiedenen Kalibrierlösungen auch bestätigen, dass die Sonde nicht exakt arbeitet.

Anhand Leitungswasser und Poolwasser sieht man die Schwankungen extrem.

Meinst du das könnte am Salzwasser liegen? Die Sonden sind eigentl. für Salzwasser geeignet. 

> Lab Grade ORP Probe
> Lab Grade pH Probe

**Comment by Buzze11** [comment]
Gute Frage. Ich habe mich bislang nur mit der gegeben Implementierung beschäftigt, weniger mit den Messwerten selbst. Ich würde vorschlagen, Du kontaktierst hierzu ggf. mal den Support von Atlas und den Sensoren. 

Viele Grüße

**Comment by Buzze11** [comment]
Closed as working as expected from Atlas Scientific EZO example comparison
